services:
  - type: web
    name: nutrisigno-backend
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.app:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: "/admin/metrics"
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SESSION_COOKIE_NAME
        value: "nutrisigno_session"
      - key: AGNOS_BASE_URL
        value: "https://SEU-ENDPOINT-AGNOS"
      - key: AGNOS_API_KEY
        sync: false
      - key: FRONTEND_HOST
        fromService:
          name: nutrisigno-frontend
          type: web
          property: host
      - key: BACKEND_HOST
        fromService:
          name: nutrisigno-backend
          type: web
          property: host
      - key: MP_WEBHOOK_SECRET
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: nutrisignov2-db
        # property padrão é connectionString; se quiser explícito:
          property: connectionString

  - type: web
    name: nutrisigno-frontend
    env: python
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run frontend/main.py --server.address 0.0.0.0 --server.port $PORT"
    autoDeploy: true
    envVars:
      - key: BACKEND_HOST
        fromService:
          name: nutrisigno-backend
          type: web
          property: host

databases:
  - name: nutrisignov2-db
    databaseName: nutrisignovii
    plan: free
    region: oregon
    ipAllowList: []